FROM node:10.13-alpine
ENV NODE_ENV production
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install
# If you are building your code for production
# RUN npm install --only=production
#RUN npm install --production --silent && mv node_modules ../

# Bundle app source
COPY . .
EXPOSE 3000
CMD npm start
